export const mockFlights = [
  {
    id: 1,
    airline: "SkyAir",
    logo: "https://ui-avatars.com/api/?name=SA&background=00a698&color=fff",
    departure: { time: "08:00 AM", city: "New York (JFK)" },
    arrival: { time: "10:30 AM", city: "London (LHR)" },
    duration: "6h 30m",
    price: 345,
    stops: "Direct",
  },
  {
    id: 2,
    airline: "Global Jet",
    logo: "https://ui-avatars.com/api/?name=GJ&background=0770e3&color=fff",
    departure: { time: "11:15 AM", city: "New York (JFK)" },
    arrival: { time: "03:45 PM", city: "London (LHR)" },
    duration: "8h 30m",
    price: 298,
    stops: "1 Stop via FRA",
  },
  {
    id: 3,
    airline: "Oceanic Air",
    logo: "https://ui-avatars.com/api/?name=OA&background=1e293b&color=fff",
    departure: { time: "06:00 PM", city: "New York (JFK)" },
    arrival: { time: "11:00 PM", city: "London (LHR)" },
    duration: "7h 00m",
    price: 412,
    stops: "Direct",
  },
  {
    id: 4,
    airline: "SkyAir",
    logo: "https://ui-avatars.com/api/?name=SA&background=00a698&color=fff",
    departure: { time: "10:00 PM", city: "New York (JFK)" },
    arrival: { time: "06:15 AM", city: "London (LHR)" },
    duration: "9h 15m",
    price: 275,
    stops: "1 Stop via CDG",
  },
  {
    id: 5,
    airline: "AeroExpress",
    logo: "https://ui-avatars.com/api/?name=AE&background=f59e0b&color=fff",
    departure: { time: "07:30 AM", city: "New York (JFK)" },
    arrival: { time: "02:00 PM", city: "London (LHR)" },
    duration: "10h 30m",
    price: 230,
    stops: "2 Stops",
  }
];
